version: "3.4"
services:
  web-api:
    build: .
    ports:
      - 5000:5000
    build: .
    depends_on: 
      - db
    command: > 
      sh -c "npm run dev"

  ml:
    build: . 
    ports:
      - 8000:8000
    depends_on: 
      - db
    command: >
      sh -c "export FLASK_APP=./routes/api/machine-learning/app.py && pipenv run serve"