version: "3"
services:
    api:
        ports:
            - '5000:5000'
        build: .
        command: >
            sh -c "npm run test && npm run dev"
        depends_on:
            - db
    db:
        image: postgres
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: messaging-app
        ports:
            - '5432:5432'

volumes:
    db-data:
        driver: local