version: "3.4"
services:
  web-api:
    build: .
    ports:
      - 5000:5000
    build: .
    depends_on: 
      - db
    command: > 
      sh -c "npm run dev"

  ml:
    build: . 
    ports:
      - 8000:8000
    depends_on: 
      - db
    command: >
      sh -c "export FLASK_APP=./routes/api/machine-learning/app.py && pipenv run serve"

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: messaging-app
    ports:
      - 5432:5432

volumes:
  db-data:
    driver: local
