version: "3.4"
services:
  web-api-tests:
    build: .
    ports:
      - 5000:5000
      - 8900:8900
    depends_on:
      - db
    environment:
      - CI=true
    command: >
      sh -c "npm run test"

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: messaging-app
    ports:
      - 5432:5432

volumes:
  db-data:
    driver: local
